### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by WHYBBE** [JustDoIt0910/SnakeBattle#1]
昨天在B站我说要pr，但今天看了看想运行你这个项目还有点费劲的，所以就不pr了，提个issue。

* 头文件中使用`using namespace std;`不太好
* 用`#pragma once`替代`#ifndef等一系列`宏定义
* 推荐使用CMake构建C/C++应用，配置环境十分舒适（这也是为什么我不能帮你改，因为帮你改了你可能就运行不起来，而且有违你的设计初衷，而且你的makefile也写得挺好的）
* 没有注释或文档，看起来有一点点费劲，类有一点点小多
* 没有`.gitignore`文件，可以按制定规则直接忽视生成的可执行文件直接Commit
* 推荐使用智能指针代替裸指针（C++11以上）
* 同时也推荐使用`std::thread`代替`pthread`（C++11以上）

这个项目你用了libevent、Makefile、qt等工具是相当不错，比我强多啦！

**Comment by JustDoIt0910** [comment]
太谢谢啦，以后会注意这些的。开学以后再把项目好好完善一下
